### Search with id > 50
POST http://localhost:8080/search
Content-Type: application/json

{
  "criteria": [
    {
      "key": "id",
      "operation": "GREATER_THAN",
      "value": 50
    }
  ]
}

### Search with name start with 'a'
POST http://localhost:8080/search
Content-Type: application/json

{
  "criteria": [
    {
      "key": "name",
      "operation": "BEGINS_WITH",
      "value": "A"
    }
  ]
}