insert into entity (id, name, description) values (1, 'Caitlin Dufaire', 'Hallucinogen abuse w psychotic disorder, unsp');
insert into entity (id, name, description) values (2, 'Rae Davydzenko', 'War operations involving fragments from munitions');
insert into entity (id, name, description) values (3, 'Bebe Morena', 'Lacerat unsp blood vessel at wrs/hnd lv of left arm, subs');
insert into entity (id, name, description) values (4, 'Madeline Strickler', 'Unspecified choroidal hemorrhage');
insert into entity (id, name, description) values (5, 'Franky Gittose', 'Unsp B-cell lymphoma, nodes of ing region and lower limb');
insert into entity (id, name, description) values (6, 'Eachelle Grimble', 'Poisoning by and adverse effect of saline and osmotic laxtv');
insert into entity (id, name, description) values (7, 'Merrielle Brough', 'Lacerat extn musc/fasc/tend r lit fngr at wrs/hnd lv, subs');
insert into entity (id, name, description) values (8, 'Duane Clayfield', 'Atrial septal defect');
insert into entity (id, name, description) values (9, 'Jard McLewd', 'Major histocompatibility complex class I deficiency');
insert into entity (id, name, description) values (10, 'Lorelei Brombell', 'Matern care for known or susp placntl insuff, 1st tri, fts2');
insert into entity (id, name, description) values (11, 'Dick Gietz', 'Benign recurrent meningitis [Mollaret]');
insert into entity (id, name, description) values (12, 'Carmine Skakunas', 'Intraop and postprocedural complications of skin, subcu');
insert into entity (id, name, description) values (13, 'Jaymie Keattch', 'Toxic effect of strychnine and its salts, acc, sequela');
insert into entity (id, name, description) values (14, 'Rora Chrispin', 'Chronic multifocal osteomyelitis, left femur');
insert into entity (id, name, description) values (15, 'Kimberly Simmons', 'Nondisp simp suprcndl fx w/o intrcndl fx r humer, 7thB');
insert into entity (id, name, description) values (16, 'Grove Rikel', 'Glaucoma secondary to eye inflammation');
insert into entity (id, name, description) values (17, 'Eliza Hiscoke', 'Nondisp fx of medial epicondyl of l humerus, init for opn fx');
insert into entity (id, name, description) values (18, 'Theo Marklew', 'Type 2 diab with mod nonp rtnop without macular edema, unsp');
insert into entity (id, name, description) values (19, 'Loraine Dunstall', 'Exudative age-rel mclr degn, left eye, with inactive scar');
insert into entity (id, name, description) values (20, 'Gerrie Arnhold', 'Nondisp fx of med phalanx of r less toe(s), 7thP');
insert into entity (id, name, description) values (21, 'Sarajane Boyce', 'Pancreatic steatorrhea');
insert into entity (id, name, description) values (22, 'Elsey McConnulty', 'Nondisp transverse fx shaft of unsp femr, 7thK');
insert into entity (id, name, description) values (23, 'Meris Iannuzzi', 'Contusion of unspecified great toe without damage to nail');
insert into entity (id, name, description) values (24, 'Tallia Havick', 'Other specified fracture of right pubis, sequela');
insert into entity (id, name, description) values (25, 'Adaline Chaves', 'Pnctr w foreign body of r idx fngr w damage to nail, subs');
insert into entity (id, name, description) values (26, 'Tanner Rapsey', 'Adverse effect of other psychostimulants');
insert into entity (id, name, description) values (27, 'Lucias Stebbings', 'Acute gastric ulcer with perforation');
insert into entity (id, name, description) values (28, 'Babbie Napthine', 'Tetracyclic antidepressants');
insert into entity (id, name, description) values (29, 'Garret Laundon', 'Acute lymphangitis of other parts of limb');
insert into entity (id, name, description) values (30, 'Chalmers Kedward', 'Person outsd hv veh inj in clsn w statnry obj in traf, sqla');
insert into entity (id, name, description) values (31, 'Eunice Wallbanks', 'Inflammatory disorders of breast');
insert into entity (id, name, description) values (32, 'Bart Gemmell', 'Breakdown of biological heart valve graft, sequela');
insert into entity (id, name, description) values (33, 'Wendell Durn', 'Keratoconus, stable, right eye');
insert into entity (id, name, description) values (34, 'Morgan Size', 'Civilian injured by military aircraft, initial encounter');
insert into entity (id, name, description) values (35, 'Rosita Buston', 'Unsp Escherichia coli as the cause of diseases classd elswhr');
insert into entity (id, name, description) values (36, 'Darbee Todari', 'Displ oblique fx shaft of unsp rad, init for opn fx type I/2');
insert into entity (id, name, description) values (37, 'Salaidh Warwick', 'Pedestrian on foot injured in collision w skateboarder, init');
insert into entity (id, name, description) values (38, 'Fredek Gatheral', 'Other secondary scoliosis, lumbar region');
insert into entity (id, name, description) values (39, 'Berte Gilligan', 'Unsp accident to commrcl fix-wing aircraft injuring occupant');
insert into entity (id, name, description) values (40, 'Syd Southcott', 'Laceration without foreign body of vagina and vulva');
insert into entity (id, name, description) values (41, 'Duffie Silveston', 'Traumatic ischemia of muscle, initial encounter');
insert into entity (id, name, description) values (42, 'Vilma Fieldgate', 'Secondary vitreoretinal degeneration, unspecified eye');
insert into entity (id, name, description) values (43, 'Noe Kelley', 'Driver of bus injured in clsn w rail trn/veh nontraf, subs');
insert into entity (id, name, description) values (44, 'Nolana Handford', 'Superficial foreign body of left thumb, sequela');
insert into entity (id, name, description) values (45, 'Melisande Shuttle', 'Cont preg aft spon abort of one fts or more, third tri, fts2');
insert into entity (id, name, description) values (46, 'Yale Cowing', 'Breakdown of carotid arterial graft (bypass), subs');
insert into entity (id, name, description) values (47, 'Yardley Andrusov', 'Laceration of pleura, initial encounter');
insert into entity (id, name, description) values (48, 'Urban Latch', 'Congenital lens malformation, unspecified');
insert into entity (id, name, description) values (49, 'Tasia Danford', 'Pnctr w fb of right lesser toe(s) w/o damage to nail, subs');
insert into entity (id, name, description) values (50, 'Hervey Archard', 'Unspecified subluxation of right little finger, subs encntr');
insert into entity (id, name, description) values (51, 'Redford Mc Combe', 'Laceration with foreign body of unspecified ear, init encntr');
insert into entity (id, name, description) values (52, 'Orton Donativo', 'Oth athletic court as place');
insert into entity (id, name, description) values (53, 'Carlos Risdale', 'Encounter for examination for insurance purposes');
insert into entity (id, name, description) values (54, 'Eugenia Fassbender', 'Osteonecrosis due to drugs, ankle, foot and toes');
insert into entity (id, name, description) values (55, 'Jacintha Kerley', 'Pathological fracture, r humerus, subs for fx w routn heal');
insert into entity (id, name, description) values (56, 'Caresa Favela', 'Oth osteopor w crnt path fx, unsp ank/ft, 7thD');
insert into entity (id, name, description) values (57, 'Marylee Reinmar', 'Burn first deg mult right fingers (nail), inc thumb, sequela');
insert into entity (id, name, description) values (58, 'Barbee Donnan', 'Idiopathic gout, unspecified elbow');
insert into entity (id, name, description) values (59, 'Mic Hallbird', 'Obst due to fb acc left in body fol inject or immuniz, subs');
insert into entity (id, name, description) values (60, 'Horatius Eccleston', 'Subluxation of C4/C5 cervical vertebrae');
insert into entity (id, name, description) values (61, 'Ward Fance', 'Duodenitis without bleeding');
insert into entity (id, name, description) values (62, 'Amara Daly', 'Non-prs chr ulcer oth prt r low leg limited to brkdwn skin');
insert into entity (id, name, description) values (63, 'Vicky Rumble', 'Infantile and juv cortical/lamellar/zonular cataract, r eye');
insert into entity (id, name, description) values (64, 'Obidiah Howton', 'Disp fx of prox 3rd of navic bone of l wrs, 7thK');
insert into entity (id, name, description) values (65, 'Etta Duncan', 'Background retinopathy and retinal vascular changes');
insert into entity (id, name, description) values (66, 'Wilton Issakov', 'Oligohydramnios, third trimester, fetus 5');
insert into entity (id, name, description) values (67, 'Hatti Gillino', 'Inj unsp musc/fasc/tend at thigh level, unsp thigh, subs');
insert into entity (id, name, description) values (68, 'Natalie Bernasek', 'Nondisp seg fx shaft of l fibula, 7thQ');
insert into entity (id, name, description) values (69, 'Miller MacEntee', 'Milt op involving explosion of aerial bomb, milt');
insert into entity (id, name, description) values (70, 'Findlay Hullett', 'Unsp inj msl/tnd lng extn msl toe at ank/ft lev,unsp ft,subs');
insert into entity (id, name, description) values (71, 'Davine Scown', 'Oth injury of peroneal artery, left leg, init encntr');
insert into entity (id, name, description) values (72, 'Porty Goad', 'Bent bone of unsp rad, 7thF');
insert into entity (id, name, description) values (73, 'Brinna Sutherden', 'Burn of unsp degree of right hand, unsp site, init encntr');
insert into entity (id, name, description) values (74, 'Rory Antonat', 'Toxic effect of smoke, accidental (unintentional), sequela');
insert into entity (id, name, description) values (75, 'Dirk Capstack', 'Arthropathy following intestinal bypass, hip');
insert into entity (id, name, description) values (76, 'Clarke Burnage', 'Bitten by other nonvenomous reptiles, initial encounter');
insert into entity (id, name, description) values (77, 'Nanon McArdell', 'Stage 2 necrotizing enterocolitis');
insert into entity (id, name, description) values (78, 'Alys Breewood', 'Other secondary chronic gout, elbow');
insert into entity (id, name, description) values (79, 'Kathrine Vidineev', 'Adhes due to fb acc left in body fol injection or immuniz');
insert into entity (id, name, description) values (80, 'Carlos Bisp', 'Monoarthritis, not elsewhere classified, right shoulder');
insert into entity (id, name, description) values (81, 'Raffarty Filyushkin', 'Displaced dome fx left acetabulum, subs for fx w routn heal');
insert into entity (id, name, description) values (82, 'Murray Collings', 'Activities involving ice and snow');
insert into entity (id, name, description) values (83, 'Gusella Smurfit', 'Oth intartic fx low end unsp rad, 7thC');
insert into entity (id, name, description) values (84, 'Bendite Tipping', 'Slip/trip w/o falling due to step into hole or opening, subs');
insert into entity (id, name, description) values (85, 'Fredek Hallihane', 'Nondisp fx of neck of right talus, subs for fx w routn heal');
insert into entity (id, name, description) values (86, 'Vachel Powers', 'Subluxation of metacarpophalangeal joint of other finger');
insert into entity (id, name, description) values (87, 'Budd Verrier', 'Nondisp artic fx head of l femr, 7thR');
insert into entity (id, name, description) values (88, 'Zorina Bengtson', 'Other mature T/NK-cell lymphomas, intrapelvic lymph nodes');
insert into entity (id, name, description) values (89, 'Gretta Hukins', 'Prsn brd/alit hv veh injured in collision w rail trn/veh');
insert into entity (id, name, description) values (90, 'Susan Prando', 'Lacerat unsp musc/fasc/tend at thigh level, left thigh, init');
insert into entity (id, name, description) values (91, 'Sigfrid Oylett', 'Disloc of unsp interphaln joint of r mid finger, sequela');
insert into entity (id, name, description) values (92, 'Rivy Itzkin', 'Unsp dislocation of unsp sternoclavicular joint, sequela');
insert into entity (id, name, description) values (93, 'Rudie Raise', 'Strain of intrinsic musc/fasc/tend thmb at wrs/hnd lv, init');
insert into entity (id, name, description) values (94, 'Nert Pottell', 'Hematoma of broad ligament');
insert into entity (id, name, description) values (95, 'Briana Keenan', 'Corrosion of second degree of ear');
insert into entity (id, name, description) values (96, 'Nikki Chastel', 'Postthrom syndrome w oth complications of unsp low extrm');
insert into entity (id, name, description) values (97, 'Sissie Tixall', 'Occupational exposure to risk factors');
insert into entity (id, name, description) values (98, 'Flor Noone', 'Gen skin eruption due to drugs and meds taken internally');
insert into entity (id, name, description) values (99, 'Jasmine Semeniuk', 'Oth psychoactv substance depend w psychotic disorder, unsp');
insert into entity (id, name, description) values (100, 'Ewan Dilliway', 'Secondary parkinsonism due to other external agents');
